package errcode

import (
	"net/http"

	"gitlab.shanhai.int/sre/library/net/errcode"
)

// 通过公共库创建业务 Error 的状态码默认是 500，如果是 API 接口 Error，需要根据实际场景指定状态码
var (
	NotFoundError = errcode.New(9000001, "not found").WithStatusCode(http.StatusNotFound)

	AliSDKInternalError                    = errcode.New(9010000, "阿里云内部错误")
	AliSDKResponseError                    = errcode.New(9010001, "阿里云响应错误")
	AliSDKResponseFormatError              = errcode.New(9010002, "阿里云响应格式错误")
	JenkinsInternalError                   = errcode.New(9010003, "Jenkins内部错误")
	GitlabInternalError                    = errcode.New(9010004, "Gitlab内部错误")
	JWTGenerateError                       = errcode.New(9010005, "JWT生成错误")
	GitlabUserStateError                   = errcode.New(9010006, "Gitlab用户状态错误")
	K8sInternalError                       = errcode.New(9010007, "K8s内部错误")
	ConfigManagerInternalError             = errcode.New(9010008, "配置中心内部错误")
	InvalidTaskStatusError                 = errcode.New(9010009, "不合法的任务状态")
	UnknownTaskActionError                 = errcode.New(9010010, "未知的任务行为")
	OtherRunningTaskExistsError            = errcode.New(9010011, "已存在其他未完成的任务").WithStatusCode(http.StatusConflict)
	NoRequiredTaskError                    = errcode.New(9010012, "找不到任何满足条件的任务").WithStatusCode(http.StatusNotFound)
	NeedCorrectAppNameError                = errcode.New(9010013, "请先初始化您的应用名")
	NotFindAliLoadBalancerError            = errcode.New(9010014, "没有找到指定的阿里云slb").WithStatusCode(http.StatusNotFound)
	NotFindAliPrivateZoneError             = errcode.New(9010015, "没有找到指定的阿里云云解析").WithStatusCode(http.StatusNotFound)
	InvalidImageCommitIDError              = errcode.New(9010016, "非法的镜像commit id").WithStatusCode(http.StatusBadRequest)
	NotFindK8sServiceIngressError          = errcode.New(9010017, "没有找到指定的K8s service ingress").WithStatusCode(http.StatusNotFound)
	AppNameDuplicateError                  = errcode.New(9010018, "该项目下应用名重复").WithStatusCode(http.StatusBadRequest)
	ContainerNameNotUniqueError            = errcode.New(9010019, "容器名(项目名加应用名)不唯一").WithStatusCode(http.StatusBadRequest)
	TaskVersionNameLengthError             = errcode.New(9010020, "版本号(项目名加应用名)长度过长").WithStatusCode(http.StatusBadRequest)
	PrometheusInternalError                = errcode.New(9010021, "Prometheus内部错误")
	PrometheusQueryEmptyError              = errcode.New(9010022, "Prometheus查不到任何数据")
	GitlabUserAuthError                    = errcode.New(9010023, "Gitlab用户鉴权错误").WithStatusCode(http.StatusUnauthorized)
	FinalStateTaskUpdateError              = errcode.New(9010024, "终止态任务无法更新").WithStatusCode(http.StatusBadRequest)
	OtherRunningImageJobExistsError        = errcode.New(9010025, "已存在其他正在打包的镜像").WithStatusCode(http.StatusConflict)
	K8sResourceNotFoundError               = errcode.New(9010026, "没有找到指定的K8s资源").WithStatusCode(http.StatusNotFound)
	ApolloInternalError                    = errcode.New(9010027, "Apollo内部错误")
	AliResourceNotFoundError               = errcode.New(9010028, "没有找到指定的阿里云资源").WithStatusCode(http.StatusNotFound)
	SentryInternalError                    = errcode.New(9010029, "Sentry内部错误")
	ExistingActiveJobsError                = errcode.New(9010030, "存在正在运行的Job").WithStatusCode(http.StatusConflict)
	LabelValueError                        = errcode.New(9010031, "Label值错误")
	SentryProjectExistsError               = errcode.New(9010032, "Sentry project已经存在").WithStatusCode(http.StatusConflict)
	IngressNotRegisteredToPrivateZoneError = errcode.New(9010033, "ingress没有注册到云解析中")
	GitlabUserNoPermissionError            = errcode.New(9010034, "没有权限进行此操作").WithStatusCode(http.StatusForbidden)
	DingTalkInternalError                  = errcode.New(9010035, "钉钉内部错误")
	CurrBranchNotMatchExpectBranchError    = errcode.New(9010036, "当前分支与预期分支不匹配").WithStatusCode(http.StatusBadRequest)
	InvalidDeployTaskParamError            = errcode.New(9010037, "任务参数无效").WithStatusCode(http.StatusBadRequest)
	InvalidImageVersionError               = errcode.New(9010038, "非法的镜像地址")
	K8sResourceNotReadyError               = errcode.New(9010039, "K8s资源未就绪")
	LogStoreIndexNotFoundError             = errcode.New(9010040, "日志仓库内索引不存在").WithStatusCode(http.StatusNotFound)
	GitlabHookExistsError                  = errcode.New(9010041, "gitlab hook已经存在").WithStatusCode(http.StatusConflict)
	GitlabHookNotExistsError               = errcode.New(9010042, "gitlab hook不存在").WithStatusCode(http.StatusNotFound)
	KongInternalError                      = errcode.New(9010043, "Kong内部错误")
	BatchCreateTaskWarningsError           = errcode.New(9010044, "批量创建任务警告").WithStatusCode(http.StatusBadRequest)
	ProjectCIJobExistsError                = errcode.New(9010045, "项目ci job已存在").WithStatusCode(http.StatusConflict)
	AliAlarmNotExistsError                 = errcode.New(9010047, "告警组不存在").WithStatusCode(http.StatusNotFound)
	DingTalkGroupNotExistsError            = errcode.New(9010048, "钉钉 token 分组不存在").WithStatusCode(http.StatusNotFound)
	ClusterNotExistsError                  = errcode.New(9010049, "集群不存在").WithStatusCode(http.StatusNotFound)
	NamespaceNotExistsError                = errcode.New(9010050, "K8s namespace不存在").WithStatusCode(http.StatusNotFound)
	DeploymentInChangeExistsError          = errcode.New(9010051, "存在状态变化中的Deployment")
	TaskPrimaryResourceNotExistsError      = errcode.New(9010052, "当前资源不存在，请重新部署").WithStatusCode(http.StatusNotFound)
	QDNSInternalError                      = errcode.New(9010053, "QDNS内部错误")
	GitLabUserNotFound                     = errcode.New(9010054, "GitLab 用户不存在").WithStatusCode(http.StatusNotFound)
	CronHPAJobRegisterFailed               = errcode.New(9010055, "cronHPA任务注册失败")
	NoApprovalProcessError                 = errcode.New(9010056, "无审批流程错误").WithStatusCode(http.StatusForbidden)
	OtherApprovalProcessExistError         = errcode.New(9010057, "存在其他审批中任务").WithStatusCode(http.StatusConflict)
	CreateTaskNoPermissionError            = errcode.New(9010058, "没有权限创建任务").WithStatusCode(http.StatusForbidden)
	NoRequiredInternalUserError            = errcode.New(9010059, "找不到满足条件的内部用户").WithStatusCode(http.StatusNotFound)
	DingTalkCallbackError                  = errcode.New(9010060, "Ding talk回调错误")
	InternalUserInternalError              = errcode.New(9010061, "Internal user内部错误")
	MongoTransactionInternalError          = errcode.New(9010062, "Mongo 事务错误")
	ApproversNotExistsError                = errcode.New(9010063, "审批人不存在错误").WithStatusCode(http.StatusNotFound)
	NoSuccessfulDeploymentError            = errcode.New(9010064, "没有找到成功的部署").WithStatusCode(http.StatusForbidden)
	DifferentHealthCheckURLError           = errcode.New(9010065, "存在不同的健康检查路径").WithStatusCode(http.StatusConflict)
	// ExtraWeightConfigExistsError 配合 entity.SetAppClusterWeightsReq.ForceUpdateAll
	ExtraWeightConfigExistsError  = errcode.New(9010066, "存在额外的权重设置").WithStatusCode(http.StatusConflict)
	KongConfigNotFoundError       = errcode.New(9010067, "没有找到指定的Kong配置").WithStatusCode(http.StatusNotFound)
	KongResourceNotFoundError     = errcode.New(9010068, "没有找到指定的Kong资源").WithStatusCode(http.StatusNotFound)
	KongBadRequestError           = errcode.New(9010069, "Kong 请求参数错误").WithStatusCode(http.StatusBadRequest)
	UnknownVendorError            = errcode.New(9010070, "未知的云服务商")
	UnsupportedK8sObjectKind      = errcode.New(9010071, "未支持的 k8s 资源类型")
	ClusterNotExistsInVendorError = errcode.New(9010072, "集群在运营商中不存在").WithStatusCode(http.StatusNotFound)
	LogConfigDisabled             = errcode.New(9010073, "日志采集器被禁用").WithStatusCode(http.StatusForbidden)
	HuaweiAPIInternalError        = errcode.New(9010074, "华为云API内部错误")
	LTSResourceAlreadyExists      = errcode.New(9010075, "华为云LTS资源已存在").WithStatusCode(http.StatusConflict)
	LTSResourceNotFound           = errcode.New(9010076, "华为云LTS资源未找到").WithStatusCode(http.StatusNotFound)
	InvalidHexStringError         = errcode.New(9010077, "无效的 hex 字符串")
	MissingReplacementConfigFile  = errcode.New(9010078, "配置中心replacement配置缺少文件").WithStatusCode(http.StatusForbidden)
	ExtraReplacementConfigFIle    = errcode.New(9010079, "配置中心replacement配置文件多于基础配置文件").WithStatusCode(http.StatusForbidden)
	LTSResourceAssociated         = errcode.New(9010080, "华为云LTS资源存在关联").WithStatusCode(http.StatusForbidden)
	DuplicatedImageTagError       = errcode.New(9010081, "镜像标签已经存在,请重新提交代码并重新构建镜像")
	QDNSTagNotFound               = errcode.New(9010082, "QDNS Tag 无法找到资源")
	FeishuInternalError           = errcode.New(9010083, "飞书内部错误")
)
